#ifndef HELP_HPP
#define HELP_HPP
const char* helpstr = {
  "     Keys : Description\n"
  "----------------------------------------------------\n"
  " h, Right : Parent directory\n"
  "  j, Down : Down\n"
  "    k, Up : Up\n"
  " l, Right : Open file/directory\n"
  " PgUp, ^U : Scroll up\n"
  " PgDn, ^D : Scroll down\n"
  "        H : Move to top of screen\n"
  "        M : Move to middle of screen\n"
  "        L : Move to bottom of screen\n"
  "        g : Go to first entry\n"
  "        G : Go to last entry\n"
  "       ^L : Redraw\n"
  "        q : Quit\n"
  "       ^G : Quit and cd\n"
  "        0 : View log\n"
  "        1 : Switch tab 1\n"
  "        2 : Switch tab 2\n"
  "        3 : Switch tab 3\n"
  "        4 : Switch tab 4\n"
  "        , : FileView simple/detail\n"
  "        . : Show/Hide dot files\n"
  "        i : Enable/Disable image preview\n"
  "        z : Arcive\n"
  "        Z : Current line to the middle of the screen\n"
  "        s : Sort files\n"
  "        e : Edit File\n"
  "    Space : Mark file\n"
  "        u : Clear marks\n"
  "        a : Invert marks (current directory only)\n"
  "        c : Mark files for copy\n"
  "        m : Mark files for move\n"
  "        d : Delete mark files\n"
  "        p : Paste\n"
  "        r : Rename current file\n"
  "       ^R : Batch rename (vidir)\n"
  "        ! : Spawn SHELL\n"
  "        n : Create file/directory\n"
  "        b : Open Bookmarks\n"
  "        / : Filter\n"
  "       ^/ : Change Filter type\n"
  "        x : Unarchive\n"
  "       ^x : Run Plugin \n"
  "Alt + key : Run Plugin \n"
  "        * : Toggle execute permission\n"
  "       ^j : scrolldown in preview\n"
  "       ^k : scrollup in preview\n"
  "        U : Unmouont Directory\n"
  "       ^a : Go to archive mount directory\n"
  "        ? : Help\n"
};
#endif
